language: cpp
dist: xenial
os: linux

branches:
  only:
    - master

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"

jobs:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages: &precise_latest_boost_packages
            - gcc-4.8
            - g++-4.8
            - clang-3.7
            - doxygen
          sources: &precise_latest_boost_sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7

before_install:
  - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
  - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

install:
  - pyenv shell 3.6
  - pip3 install --upgrade pip
  - pip3 install conan sphinx
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - conan --version

  # Download and install recent cmake
  - if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
    CMAKE_URL="https://cmake.org/files/v3.18/cmake-3.18.0-Linux-x86_64.tar.gz";
    mkdir -p ${DEPS_DIR}/cmake;
    travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake;
    export PATH=${DEPS_DIR}/cmake/bin:${PATH};
    fi

script:
  - cd ${TRAVIS_BUILD_DIR}/docs
  - pip3 install -r requirements.txt
  - cmake  ${CMAKE_OPTIONS}  -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=${CXX_FLAGS} CMakeLists.txt
  - make
  - mkdir html/html
  - echo "<meta http-equiv=\"refresh\" content=\"0; URL='../'\" />" > html/html/index.html
  # Disable jekyll
  - touch html/.nojekyll

deploy:
  provider: pages
  repo: ds4dm/ZERO
  strategy: git
  target_branch: docs
  token: $GITHUB_TOKEN
  keep_history: true
  name: ZEROBot
  email: zero@dragotto.net
  local_dir: ./docs/html
  on:
    branch: master

