language:
  - cpp
dist: xenial
os: linux


env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
       apt:
         packages: &precise_latest_boost_packages
           - gcc-4.8
           - g++-4.8
           - clang-3.7
         sources: &precise_latest_boost_sources
           - ubuntu-toolchain-r-test
           - llvm-toolchain-precise-3.7
    
before_install:
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

install:
    - pyenv shell 3.6
    - pip install --upgrade pip
    - sudo pip install conan sphinx breahe exhale
    - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - conan --version
    
    # Download and install recent cmake
    - if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
         CMAKE_URL="https://cmake.org/files/v3.18/cmake-3.18.0-Linux-x86_64.tar.gz";
         mkdir -p ${DEPS_DIR}/cmake;
         travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake;
         export PATH=${DEPS_DIR}/cmake/bin:${PATH};
       fi
  
script:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake  ${CMAKE_OPTIONS}  -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=${CXX_FLAGS} CMakeLists.txt
  - make
  
after_success:

